spring:
  application:
    name: user-profile-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true

  datasource:
    url: jdbc:mysql://prod-db-host:3306/ailearn
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
